### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by edwinperaza** [fujiyuu75/Sequent#17]
Hi, 

When I see your example on readme.MD `.anim(int)` just need an integer but when I implement it is mandatory to pass a Context. I guess, could be fine if you can update Readme.md file.

Thanks.

**Comment by fujiyuu75** [comment]
Hi,

I fix Readme.md from ```.anim(int)``` to ```.anim(Context, int)```.

Thanks @edwinperaza
